### ISSUE TITLE
官网评论区bug

### ISSUE THREAD

**Issue by garfeng** [wa-lang/wa#10]
没登录时，能显示评论框，但不能评论. 

登录后，评论框变成了一组 json

![image](https://user-images.githubusercontent.com/19792314/182298123-a53ee08f-9d9e-4e1b-bb04-f2f1bcdc528f.png)

**Comment by chai2010** [comment]
不懂前端，我们本地都是好的

**Comment by garfeng** [comment]
没登录是好的，登录后就变成了黑色的代码框。

![image](https://user-images.githubusercontent.com/19792314/184495401-5609af11-856e-4e56-a72a-db90726fb96a.png)
