### ISSUE TITLE
二进制码中文版建议

### ISSUE THREAD

**Issue by LTreeshu** [wa-lang/wa#11]
[占坑]我建议凹语言的二进制码可以加个中文版，如:
1010011010
凸凹凸凹凹凸凸凹凸凹

**Comment by nobodxbodon** [comment]
是为增加二进制码的可读性吗？在何种使用场景下会阅读二进制码呢？
个人在重现木兰时不时会调试和阅读语法树，也许对语法树节点名称的本地化更有实用性？
