### ISSUE TITLE
中文辅助插件

### ISSUE THREAD

**Issue by nobodxbodon** [wa-lang/wa#15]
看到 [补全辅助插件](https://wa-lang.org/smalltalk/st0003.html#ide%E4%B8%AD%E6%96%87%E6%8F%92%E4%BB%B6%E5%A4%AA%E7%83%82) ，个人之前打过一点下手。此插件的好处是，即便尚无vsc下的语言支持插件，此插件仍会按照纯字符串进行补全，关键词或标识符都是：
<img width="516" alt="Screen Shot 2022-08-06 at 11 57 25 AM" src="https://user-images.githubusercontent.com/392497/183262590-1baff496-5f54-4d2f-8334-07bbdd8be689.png">
<img width="464" alt="Screen Shot 2022-08-06 at 11 57 45 AM" src="https://user-images.githubusercontent.com/392497/183262591-5f0f2afe-c53b-4dff-9224-a67780fea37c.png">

且此插件支持全拼之外的五笔等输入法。

另外，还有IntelliJ下类似插件： https://github.com/tuchg/ChinesePinyin-CodeCompletionHelper 。对了，IntelliJ系列IDE从2022版开始就已默认支持拼音缩写补全，无上面插件的效果如下：
<img width="616" alt="Screen Shot 2022-08-06 at 12 02 16 PM" src="https://user-images.githubusercontent.com/392497/183262792-2d8362de-1dab-447c-9b45-00848e9aa6c4.png">

就我了解此补全插件需依赖ide的语言支持插件。

VS也有 [类似插件](https://marketplace.visualstudio.com/items?itemName=msdn5.ChineseAssistant)。

**Comment by chai2010** [comment]
可以加微信助手标注期望开放的方向
