### ISSUE TITLE
我比较好奇中文编程真的能增加代码可读性吗? 

### ISSUE THREAD

**Issue by tonyqus** [wa-lang/wa#16]
如题

**Comment by alai7150** [comment]
好多中文编程语言最后不都是搞的套壳吗？我们绝大多数人都在应用层，没有到内核和编译器层面，因为无利可图。

**Comment by chai2010** [comment]
@alai7150 你说的对，凹从来没有说有什么创新之处，我们是只是要打造一个码农自己用的锄头。计算机科学家们就别来掺和了

**Comment by ObcbO** [comment]
会降低写代码的效率
