### ISSUE TITLE
年轻人，大有可为，加油干

### ISSUE THREAD

**Issue by cnmade** [wa-lang/wa#2]
发明编程语言绝非易事。
指望不上中科院那帮秀才了。

这几位年轻人，勇气可嘉。
希望你们不忘初心牢记使命，造出最好的编程语言。
不要怕，不要怂，就是干。
在茫茫编程语言的海洋里，杀出一条自己的路。

先是学习和模仿别人。然后再发明创造。

**Comment by luyifanlu** [comment]
还有清北那一般，
