### ISSUE TITLE
砍掉对 llir 的依赖

### ISSUE THREAD

**Issue by chai2010** [wa-lang/wa#26]

**Comment by slince** [comment]
`llir` 好像并没有成熟的应用出现，仓库 [`readme`](https://github.com/llir/llvm) 上的应用也基本都弃坑了；不如效仿 `tiny-go` 使用 `cgo` 和 `llvm` 集成

**Comment by benshi001** [comment]
Removed in https://github.com/wa-lang/wa/commit/2e552692a477bf870e1480fcc5681cb09b017226
