### ISSUE TITLE
 开发流程建议：是否采用PEP 文档驱动

### ISSUE THREAD

**Issue by cnmade** [wa-lang/wa#3]
开发流程建议：是否采用PEP 文档驱动
1. 先提一个issue，
2. 针对这个issue，写一个改进PEP文档
3. 投票决定是否接受
4. 对接受的文档，进行开发
5. 提交代码审核
6. 代码合并
7. 文档标记完成

参见python的开发流程

**Comment by csukuangfj** [comment]
现在所有的 commits 都是直接 push 到 master, 连一个PR 都没有。

不知道作者们是不是不希望别人对他们的代码进行 review.

**Comment by cnmade** [comment]
@csukuangfj 感兴趣就加入，提出自己的意见和建议，帮助构建和谐文明发展的社区。
刚开始是几个人的兴趣项目。这个很容易理解。

不过做大做强，一定是需要一定的流程和规范

不然林子大了，什么鸟都有。
有的 鸟是好的，有的鸟有点坏。

**Comment by chai2010** [comment]
PEP流程再完美，也不会出现一个新的Python。我觉得流程不是刻意为之，是为了提供更好的效率，而不是为了成为负担。

@csukuangfj 不瞒你说，我个人是比较鄙视各种流程的（包括PR流程），启这种项目首先是要自己爽。如果您要贡献的代码和我们的目标一致自然欢迎，如果目标不一致您再新开一个项目不是更好吗。

总之，一切随缘

**Comment by cnmade** [comment]
我是法制派，非自由派。
律法的意义在于，提供了一种公良秩序。
如果没有秩序，那可能就无限制的野蛮。

总之，不在此过多的讨论这之间的道理和分别，歌声动人，只唱给知音听。


也对项目开发者和对项目定位有了清晰的认知。
感谢告知你们所想所思。

祝安康。
