### ISSUE TITLE
包管理器的设计：是否采用npm,cargo, opam, 或者采用bazel build等成熟的构建工具？

### ISSUE THREAD

**Issue by cnmade** [wa-lang/wa#4]
包管理器的设计：是否采用npm,cargo, opam, 或者采用bazel build等成熟的构建工具？

千万不要再去用cmake。。

这个逼玩意。。恨得不行。

**Comment by 3dgen** [comment]
包管理完全可以另开一个项目嘛，我们的目标是：人人有坑占，嘿

**Comment by cnmade** [comment]
有本书叫《乌合之众》，如果不能很好的组织起来，那等于白瞎。没有目标，没有组织，散兵游勇，做不了事。

**Comment by chai2010** [comment]
为什么需要别人组织呢？如果需要别人组织指导，那这个项目应该不会存在吧。
对于包管理，[hello](https://github.com/wa-lang/wa/tree/master/_examples/hello) 例子已经有了目录结构，只要把依赖的包更新到 vendor 目录就成了。
