### ISSUE TITLE
不懂是我没看明白还是写的太简略了

### ISSUE THREAD

**Issue by yxj1028530975** [wa-lang/wa#5]
这是为了创语言而创语言吗。。。

**Comment by csukuangfj** [comment]
https://github.com/wa-lang/wa/blob/master/docs/goals.md

**Comment by 3dgen** [comment]
讲个故事：2016年受命开发一个Web应用，作为一个C系老炮/Go新手/JS菜鸡，当真是一脸懵逼，然后就发现了Emscripten这个狼牙棒，最后以C内核+JS界面组成脸、Go组成屁股的形式交活了事。期间踩坑无数罄竹难书（啊不对，中途搞出了那本《面向WebAssembly编程》）。
最近想鼓捣一个小玩意，又遇到了技术栈选型的问题，但是老坑依然在：不想再手动管理内存了、有几个关键组件只有C系版本但是cgo性能太弱鸡了、不想同一套处理逻辑在前后端用两种不同的语言分别实现了……
起义军自己打造刀具是拿去卖钱的么？显然不是嘛……

**Comment by chai2010** [comment]
> https://github.com/wa-lang/wa/blob/master/docs/goals.md
> 
> 这个里面没有写创建这个语言是为了解决什么问题。
> 
> 我为什么不选择 go/rust/c++, 而要用这个语言呢？

作为使用者，建议您选择 go/rust/c++ 这些成熟的语言。
但是如果您是语言设计者，你就自然会尝试用你自己设计的语言……
