### ISSUE TITLE
为什么定义函数要用 fn 而不是 func 呢？

### ISSUE THREAD

**Issue by gochief** [wa-lang/wa#6]
我觉的 func 会比 fn 优雅一些

**Comment by csukuangfj** [comment]
rust 用的就是 fn

**Comment by ALuoBo** [comment]
来点中国人的折中吧 2333， 建议用  fun 来定义函数

**Comment by chai2010** [comment]
我也不知道为什么，也可以是用function、fun、fxxk……

**Comment by 3dgen** [comment]
> 来点中国人的折中吧 2333， 建议用 fun 来定义函数

说不定可以支持自定义关键字

**Comment by HugoLei** [comment]
我觉得可以用拼音 “hanshu”

**Comment by chai2010** [comment]
> 我觉得可以用拼音 “hanshu”

很好的提议，可以和汉字并列👍最终可以弄个投票决定
