### ISSUE TITLE
Incorrect Finalizer Behavior and WASM Runtime Error

### ISSUE THREAD

**Issue by pigpigyyy** [wa-lang/wa#61]
## Description

Using the `setFinalizer` function with the following code causes incorrect output for `println(x.i)`. Changing the `i` field in `X` from `i32` to `i64` leads to a WASM runtime error.

## Code to Reproduce

```go
type X struct {
  i: i32
}

func final(x: X) {
  println(x.i)
}

func main {
  x := &X{i: 123}
  setFinalizer(x, final)
  x = nil
}
```

## Observed Behavior

1. `println(x.i)` prints an incorrect value.
2. Changing `i` to `i64` results in a WASM runtime error.

## Expected Behavior

1. `println(x.i)` should output the assigned value (123).
2. Changing `i` to `i64` should not cause runtime errors.

## Environment

wa-lang version: 0.19.0

**Comment by 3dgen** [comment]
First of all, congratulations on discovering a hidden feature of Wa.
The signature of the finalizers should be like this:
```wa
func final(ptr: u32)
```
While `ptr` is the raw pointer of the obj that will be release later, it's not the obj's value.
So the correct code is as follows:

```wa
type X struct {
  i: i64
}

func final(ptr: u32) {
    x := _getX(ptr)
    println(x.i)
}

#wa:runtime_getter
func _getX(ptr: u32) => X

func main {
  x := &X{i: 123}
  setFinalizer(x, final)
  //x = nil // this line is not necessary
}
```

The `#wa:runtime_getter` tag helps create a function that load obj from a raw pointer.
