### ISSUE TITLE
类yaml语法风格能否加入？

### ISSUE THREAD

**Issue by Baiyuetribe** [wa-lang/wa#8]
纵观现代编程，类yaml格式的编程最符合人脑阅读习惯，比如前端用于编写html的`pug`语法、写css用的`stylus`、以及`python`语言，这些都是非常高效的编程风格。假如能在go语言这种简单关键字基础上融入yaml风格的编程，无疑会成为最受关注的语言。目前很多个括号{}看着不舒服，编写也一样

当然以上只是个人观点，也是对未来编程语言发展的个人看法。特别喜欢go，要是能去掉各种花括号，改为yaml格式，无疑是未来编程必走之路

**Comment by chai2010** [comment]
这是配置语言常规语法糖，比如 [CUE](https://github.com/cue-lang)、[KCL](https://github.com/kusionStack/kclvm)，这些确实是通用编程语言可以借鉴的地方。但是目前还在解决温饱的阶段，暂时没有精力考虑
